### ISSUE TITLE
remove module key from yaml framework

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#102]
Here is an example yaml file from https://github.com/HPC-buildtest/buildtest-configs/blob/master/contrib/shahzebsiddiqui/helloworld/hello.yml 

```
testblock: singlesource
test:
    source: hello.c
    flags: -O3
    compiler: gnu
    module:
      - gcc
```

specifying module name in yaml is not a good idea. Initial idea was to have it lower case, but every site will have different names and it makes it difficult to specify this in configuration file. Instead this key should be removed from all test and it would be handled by buildtest through different mechanism
