### ISSUE TITLE
Add a 'summary' field in buildspec 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1059]
The `summary` field can can be used to describe a test which can be used as extended description. Currently the `description` field is limited to 80 char defined in https://github.com/buildtesters/buildtest/blob/devel/buildtest/schemas/definitions.schema.json

```
    "description": {
      "type": "string",
      "description": "The ``description`` field is used to document what the test is doing",
      "maxLength": 80
    },
```

The idea would be to include similar field without any `maxLength`. This would be applied to all schemas including `script`, `compiler`, and `spack`.

A typical test could be something like

```
buildspecs:
  summary_example:
    type: script
    description: Short description limited to 80 characters
    summary: |
      This is a long description of test that 
      can exceed 80 characters and be multiline 
   executor: generic.local.bash
   run: pwd
```

- [x] Update schema  https://github.com/buildtesters/buildtest/blob/devel/buildtest/schemas/definitions.schema.json and add property to other schemas such as script schema https://github.com/buildtesters/buildtest/blob/devel/buildtest/schemas/script.schema.json
- [x] Add an example test in https://github.com/buildtesters/buildtest/tree/devel/buildtest/schemas/examples to ensure schema validates with `summary` field. 
- [x] Ensure test pass via regression test. Run via `python $BUILDTEST_ROOT/buildtest/tools/unittest.py -c` or `buildtest unittests -c`. See https://buildtest.readthedocs.io/en/devel/contributing/regression_testing.html
- [x] Add example buildspec in https://github.com/buildtesters/buildtest/tree/devel/tutorials for documentation purposes. 
- [x] Document this field in https://github.com/buildtesters/buildtest/blob/devel/docs/buildspecs/buildspec_overview.rst
