### ISSUE TITLE
specify MODULEPATH when searching for compilers

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1185]
Currently buildtest will search for compilers (`buildtest cg compilers find`) via MODULEPATH and it will use whatever the system default MODULEPATH is set. We can allow this to by dynamically changed during the search since MODULEPATH can be a list of many directories and running `buildtest cg compilers find` or `buildtest cg compilers test` can test a very long time.


Therefore i propose the following we add an optional argument ``buildtest cg compilers --modulepath=<dir1>:<dir2>`` set MODULEPATH prior to finding compilers.

Secondly we can add this to configuration file where we set MODULEPATH. This could be set in configuration file in same level as `find` with keyword `modulepath` that accepts a list of directories. 

```
# compiler block                                                                                                                                                                                                                  
compilers:         
  modulepath: ['/tmp', '/var/']                                                                                                                                                                                                               
  find:
    gcc: "^(gcc)"                                                                                                                                              
```

In order to make this happen we need to do the following:

- [x] Update [settings.schema.json](https://github.com/buildtesters/buildtest/blob/devel/buildtest/schemas/settings.schema.json) with support for 'modulepath' keyword
- [x] Add new option `buildtest cg compilers --modulepath` in https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/__init__.py
- [x] Implement logic in https://github.com/buildtesters/buildtest/blob/devel/buildtest/cli/compilers.py. Note when using `Lmod` one will call the Spider class from Lmodule. 

https://github.com/buildtesters/buildtest/blob/a7996718142cb30a2a6bccdf2dbed3ada87fdf52/buildtest/cli/compilers.py#L203-L206

The __init__ method of `Spider` class will accept a list of directories from MODULEPATH to get the modules

https://github.com/buildtesters/lmodule/blob/e0242505dae800789beeb81e57a9698db2a83188/lmod/spider.py#L19-L39

This is then retrieved by calling `get_modules` method

https://github.com/buildtesters/lmodule/blob/e0242505dae800789beeb81e57a9698db2a83188/lmod/spider.py#L68-L99

Which is invoked by buildtest

https://github.com/buildtesters/buildtest/blob/a7996718142cb30a2a6bccdf2dbed3ada87fdf52/buildtest/cli/compilers.py#L208

As per `environment-modules` logic we use `module av -t` to get list of modules that is processed, we should change it such that it will process the files belonging to MODULEPATH. One way is to get this detail is to build a list of files by iterating over the directories in MODULEPATH. The method `_validate_modules` will eventually test all the files anyways we just need to pass the list

https://github.com/buildtesters/buildtest/blob/a7996718142cb30a2a6bccdf2dbed3ada87fdf52/buildtest/cli/compilers.py#L260-L289
