### ISSUE TITLE
symlink check for status

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1330]
similar to #1327 where we check for files we can have a check for symbolic link checks.

This could be done something like this with a field name `is_symlink` which expects a list of values that are checked for symbolic link

```
buildspecs:
 symlink_test:
   type: script
   executor: generic.local.bash
   description: status check based on symbolic link
   run: |
      ln -s /tmp scratch
   status:
     is_symlink:
       - scratch
```
