### ISSUE TITLE
capture metrics from arbitrary file names 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1417]
Currently, metrics can capture from stdout/stderr as in this example from https://buildtest.readthedocs.io/en/devel/writing_buildspecs/performance_checks.html#defining-metrics

```yaml
buildspecs:
  metric_regex_example:
    executor: generic.local.sh
    type: script
    description: capture result metric from output
    run: echo "HPCG result is VALID with a GFLOP/s rating of=63.6515"
    tags: tutorials
    metrics:
      hpcg_rating:
        type: float
        regex:
          exp: '(\d+\.\d+)$'
          stream: stdout

      hpcg_state:
        type: str
        regex:
          exp: '(VALID)'
          stream: stdout
```

We need to add support for arbitrary file names during performance checks. Therefore we can add another field such as `file_regex` as a property  so it could be something like this

```yaml
buildspecs:
  metric_regex_example:
    executor: generic.local.sh
    type: script
    description: capture result metric from output
    run: echo "HPCG result is VALID with a GFLOP/s rating of=63.6515" > hpcg.txt
    tags: tutorials
    metrics:
      hpcg_rating:
        type: float
        file_regex:
          exp: '(\d+\.\d+)$'
          file: hpcg.txt

      hpcg_state:
        type: str
        file_regex:
          exp: '(VALID)'
          file: hpcg.txt
```

if there is a regex mismatch or file doesn't exist or is not a file then metrics is undefined. This can be later used in any of the status check such as `assert_ge`.

**Comment by shahzebsiddiqui** [comment]
@wyphan @prathmesh4321 
now that i am thinking about this i think we can remove `file_regex` and just use `regex` but have a property `file` that is a sub-property of `regex`. Since the logic of `regex` and `file_regex` is same just which file gets read we can have `file` or `stream` be required property but only one can be specified with this change we can see changes to `metrics` as follows

```yaml
buildspecs:
  metric_regex_example:
    executor: generic.local.sh
    type: script
    description: capture result metric from output
    run: echo "HPCG result is VALID with a GFLOP/s rating of=63.6515" > hpcg.txt
    tags: tutorials
    metrics:
      hpcg_rating:
        type: float
        regex:
          exp: '(\d+\.\d+)$'
          file: hpcg.txt

      hpcg_state:
        type: str
        regex:
          exp: '(VALID)'
          file: hpcg.txt
```

Similarly we can have the same test capture metrics using `stream`

```yaml
buildspecs:
  metric_regex_example:
    executor: generic.local.sh
    type: script
    description: capture result metric from output
    run: echo "HPCG result is VALID with a GFLOP/s rating of=63.6515" 
    tags: tutorials
    metrics:
      hpcg_rating:
        type: float
        regex:
          exp: '(\d+\.\d+)$'
          stream: stdout

      hpcg_state:
        type: str
        regex:
          exp: '(VALID)'
          stream: stdout
```


Currently, we have a slight difference in `regex` and `file_regex` under status, the `regex` is a single match whereas `file_regex` is an array of regex match.  see https://buildtest.readthedocs.io/en/devel/buildspecs/buildspec_overview.html#passing-test-based-on-regular-expression and https://buildtest.readthedocs.io/en/devel/buildspecs/buildspec_overview.html#specify-regular-expression-on-arbitrary-filenames

```yaml

buildspecs:
  status_regex_pass:
    executor: generic.local.bash
    type: script
    tags: [system]
    description: Pass test based on regular expression
    run: echo "PASS"
    status:
      regex:
        stream: stdout
        exp: "^(PASS)$"

  status_regex_fail:
    executor: generic.local.bash
    type: script
    tags: [system]
    description: Pass test based on regular expression
    run: echo "FAIL"
    status:
      regex:
        stream: stdout
        exp: "^(123FAIL)$"
```

```yaml
buildspecs:
  regex_on_multiple_files:
    type: script
    executor: generic.local.bash
    description: Test regex on multiple files
    run: |
      echo "Hello" > hello.txt
      buildtest --help > buildtest_help.txt
    status:
      file_regex:
        - file: hello.txt
          exp: '^(Hello)$'
        - file: buildtest_help.txt
          exp: '^(usage: buildtest)'

  regex_on_directory_not_supported:
    type: script
    executor: generic.local.bash
    description: Test regex on directory is not supported
    run: |
      mkdir -p hello
      echo "Hello" > hello/hello.txt
    status:
      file_regex:
        - file: hello
          exp: '^(Hello)$'

  file_expansion_supported:
    type: script
    executor: generic.local.bash
    description: Test regex with variable and shell expansion
    run: |
      echo "Hello" > $BUILDTEST_ROOT/hello.txt
      echo "Hello" > $HOME/hello.txt
    status:
      file_regex:
        - file: $BUILDTEST_ROOT/hello.txt
          exp: '^(Hello)$'
        - file: ~/hello.txt
          exp: '^(Hello)$'
```

We could potentially leverage the features of `file_regex` into `regex` for multiple status check and not have to release a new key to perform file check by stream so we could have something like this

```yaml
buildspecs:
  regex_on_multiple_files:
    type: script
    executor: generic.local.bash
    description: Test regex on multiple files
    run: |
      echo "Hello" > hello.txt
      buildtest --help > buildtest_help.txt
    status:
      regex:
        - file: hello.txt
          exp: '^(Hello)$'
        - stream: stdout
          exp: '^(usage: buildtest)'
```

Note that under `metrics` the `regex` won't be a list that is similar to how it behaves under `status` so it would not be correct to have the following

```yaml
buildspecs:
  metric_regex_example:
    executor: generic.local.sh
    type: script
    description: capture result metric from output
    run: echo "HPCG result is VALID with a GFLOP/s rating of=63.6515" > hpcg.txt
    tags: tutorials
    metrics:
      hpcg_rating:
        type: float
        regex:
          - file: hpcg.txt
            exp: '(\d+\.\d+)$'
          - stream: stdout
            exp: '(\d+\.\d+)$'
 ```
