### ISSUE TITLE
status check support with logical AND

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1418]
currently each status check is evaluated separately and we perform a logical OR on all the status check to evaluate the final `state` of test https://github.com/buildtesters/buildtest/blob/6458ab865c5a7f680c0d2ae98f0314584801804c/buildtest/builders/base.py#L1052-L1076

What we need is an option to control between logical OR or AND operation we could do this by adding a property let's say `mode` which could be an optional field. Valid values are [`or`, `and`]. If field is not specified we will assume `or`. In the following test, we perform status check with `returncode` and `file_exists`. The first test will fail while second test will pass. Note both test do the example same assertion except for the field `mode`.

```yaml
buildspecs:
   status_check_logical_and:
     type: script
     executor: generic.local.bash
     description: logical and assertion on status check
     run: mkdir foo
     status:
       mode: 'and'
       returncode: 1
       file_exists:
         - foo
   status_check_logical_or:
     type: script
     executor: generic.local.bash
     description: logical and assertion on status check
     run: mkdir foo
     status:
       mode: 'or'
       returncode: 1
       file_exists:
         - foo                 
```
