### ISSUE TITLE
[FEATURE]: add support for controlling maximum number of jobs per executor

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1452]
### Please describe your feature

in https://github.com/buildtesters/buildtest/blob/devel/buildtest/schemas/settings.schema.json we have a key property `max_jobs` defined that can be used to control number of jobs that can be run per executor. We should first try to implement this feature for batch jobs where `max_jobs` signify number of concurrent jobs that can be running at a given time.

We can have the following setup

```yaml
executors:
  # total across all executors in a single run
  max_jobs: 50
  local:
     # maximum number of jobs running across all local executors
    max_jobs: 20
    bash:
      shell: bash
       # maximum number of jobs running within a executor
      max_jobs: 5
  slurm:
    regular:
      qos: regular
      max_jobs: 2
```

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue
