### ISSUE TITLE
[FEATURE]: add support for removing executors from configuration file

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1609]
### Please describe your feature

add support in buildtest to remove executors via command line. 

We can introduce a command name `buildtest config executors remove` which takes positional argument to remove executors by name.

Let's say we have the following executors as shown below 

```
(buildtest)  ~/Documents/github/buildtest/ [devel*] buildtest cg executors   
generic.local.sh
generic.local.csh
generic.local.zsh
```
If we want to remove the zsh executor we could do `buildtest config executors remove generic.local.zsh` and this will remove the section for `zsh` which would be the section for `zsh` under the executors section

```
(buildtest)  ~/Documents/github/buildtest/ [devel*] buildtest cg executors -y
executors:
  local:
    bash:
      description: submit jobs on local machine using bash shell
      shell: 123bash
    csh:
      description: submit jobs on local machine using csh shell
      shell: csh
    sh:
      description: submit jobs on local machine using sh shell
      shell: sh
    zsh:
      description: submit jobs on local machine using zsh shell
      shell: zsh

```

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue
