### ISSUE TITLE
[FEATURE]: extract multiple lines from metrics

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#1759]
### Please describe your feature

Some example for multiple lines. The `linenum` can be a list of integers used to extract a line. In this case we will extract line 1, 2, 4 and apply regular expression

```yaml

buildspecs:
  metric_regex_linenum_failure_example:
    executor: generic.local.bash
    type: script
    description: invalid linenum can result in failure
    run: |
      echo "This is line: 1"
      echo "This is line: 2"
      echo "This is line: 3"
      echo "This is line: 4"
    tags: tutorials
    metrics:
      second_line:
        type: str
        regex:
          exp: 'This is line: \d'
          stream: stdout
          linenum: [1, 2, 4]
```

Another idea would be to keep it a string but a bit more complex we need to split by comma and make some logic. For instance the `3-5` need to be evaluated as a range of lines this would allow for range of lines.

```yaml
buildspecs:
  metric_regex_linenum_failure_example:
    executor: generic.local.bash
    type: script
    description: invalid linenum can result in failure
    run: |
      echo "This is line: 1"
      echo "This is line: 2"
      echo "This is line: 3"
      echo "This is line: 4"
    tags: tutorials
    metrics:
      second_line:
        type: str
        regex:
          exp: 'This is line: \d'
          stream: stdout
          linenum: "1,2,3-5"
```

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue
