### ISSUE TITLE
better way to handle variables  in a test-configuration

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#245]
Here is an example at Stampede2 https://github.com/HPC-buildtest/buildtest-stampede2/blob/master/apps/serial/hello.yml that illustrates the need for having variable defined in one location either in the buildtest configuration (default.yml) or something specific to the test configuration.

The issue is i will need to redeclare this variable per sub-test and that get's repetitive. This could be a variable defined once in buildtest-configuration. If i were to do it, it would be something like this in configuration file

```
vars:
  ROOT: $WORK/buildtest-stampede2
  APP_ROOT: $ROOT/apps
  SCHED_ROOT: $ROOT/sched  
```

In the configuration i can reference the source files assuming variable is defined automatically as part of script generation.
