### ISSUE TITLE
Method for selecting default executor

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#251]
So here are few ideas on how we can select a default executor as per configuration.

Option 1: Add key ``default`` in executor class
--------------------------------------------------

It would be something like this

```
editor: vi
executors:
  default: runlocal
  normal:
    type: slurm
    description: submit jobs with slurm using srun instead of sbatch
    launcher: sbatch
    options:
      - "-p normal"
      - "-t 00:10"
      - "-N 1"
      - "-n 1"
  runlocal:
    type: local
    description: submit jobs locally
```

We would need to check value of ``default`` after the validate step against all executor objects since we won't know the executor names after the validate step. Json can't use ``enum`` in this case since the executor object name is not defined yet

Option 2: First executor object is default
----------------------------------------------
 
In this case, we don't need to add a separate key (``default``) to make the change. it's just a matter of order. In both case, the default executor does not have to be of ``type: local``. This is true, because we have not made strict check to ensure we have a local executor, if we wanted to we would have to change the json schema.

Option 3: Default per type
-----------------------------

Not sure if this would even make sense but having a default per executor type (``local``, ``slurm``). Here would be an example of two ``local`` and ``slurm`` executor definition with a default executor for each type

```
editor: vi
executors:
  default: 
    local: runlocal
    slurm: normal

  normal:
    type: slurm
    description: submit jobs with slurm using srun instead of sbatch
    launcher: sbatch
    options:
      - "-p normal"
      - "-t 00:10"
      - "-N 1"
      - "-n 1"
  admin:
    type: slurm
    description: run jobs on admin partition
    launcher: sbatch
    options:
      - "-p admin"
  runlocal:
    type: local
    description: submit jobs locally
  
  run_root:
    type: local
    description: run jobs that require root priviledges (root)
```

The behavior of buildtest can change as user change the default executor, it going to be important that their test are compatible when they make change to default executor.
