### ISSUE TITLE
Invalid configuration passing validation

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#253]
This configuration is passing check, there should not be any extra parameters passed to local executor the key ``extraOptions`` should be caught with json schema.  Their is an issue with use of ``additionalProperties: false`` which is not working in child object. See https://json-schema.org/understanding-json-schema/reference/object.html for more details and issue described in PR #249 

```
gitpod /workspace/buildtest-framework $ buildtest config view
editor: vi
executors:
  runlocal:
    type: local
    description: submit jobs locally
    extraOptions: var
```
