### ISSUE TITLE
exclude configs from being processed in a directory.  

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#267]
Okay so i know this is going to be needed when i run stampede2 test i can just do ``buildtest build -c tests`` which will run all these tests

```
tests/
├── apps
│   ├── openmp
│   │   ├── hello.yml
│   │   └── src
│   │       └── omp_hello.c
│   └── serial
│       ├── hello.yml
│       └── src
│           ├── hello.c
│           ├── hello.cpp
│           └── hello.f90
├── sched
│   ├── failed_jobs.yml
│   ├── jobs.yml
│   └── partitions.yml
├── system
│   ├── account_alias.yml
│   ├── bzip2_compression.yml
│   ├── check_login.yml
│   ├── dns.yml
│   ├── env.yml
│   ├── idev.yml
│   ├── kernel.yml
│   ├── module.yml
│   ├── mount.yml
│   ├── selinux.yml
│   ├── shared_fs.yml
│   ├── systemd.yml
│   └── timezone.yml
└── utils
    └── tacc_help.yml

```

There are some test that would get scheduled to scheduler that may take a long time, there is no timeout on test so either we need to have some option in command line to exclude a test. Something like: ``buildtest build -c tests/ -x tests/sched/partitions.yml`` The -x for exclude could be used for specifying multiple configs maybe separated by a comma. The other option is have a key maybe called ``skip: True`` as part of a sub-test or part of the global config which skips all tests.

Something like this if its per subtest

```
version: 0.0.1
test1:
  skip: True
  type: script
  description: dummy test
  run: echo "dummy"
```

Or part of global configs such that it skips all tests something like this

```
version: 0.0.1
skip: True
test1:

  type: script
  description: dummy test
  run: echo "dummy"
```

Or we can go more crazy by skip by name of subtest so that user can do something like this which will skip test1 and test2

```
version: 0.0.1
skip: [ "test1", "test2" ]
test1:
  type: script
  description: dummy test
  run: echo "dummy"
test2:
  type: script
  description: dummy test
  run: echo "dummy"
test3:
  type: script
  description: dummy test
  run: echo "dummy"
```
