### ISSUE TITLE
permutation of single test across multiple modules 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#275]
There is a use-case to test a single application let' say dgemm and sgemm with several intel modules. Test can be found in the following links:
- https://github.com/HPC-buildtest/buildtest-stampede2/blob/master/tests/apps/mkl/dgemm.yml
- https://github.com/HPC-buildtest/buildtest-stampede2/blob/master/tests/apps/mkl/sgemm.yml

Right now i need to duplicate the test once per module ``intel/18.0.2``, ``intel/17.0.3``, ``intel/16.0.4``. I dont want to write one monolithic test in ``run`` to load and unload modules while testing, likewise i'd want a test script per module file generated such that the output is apparent that we are testing this application **dgemm** with **module version X.Y**. 

Considering HPC supports many version of a package, i think this use-case will be prevalent when one needs to test software across version.

@vsoch any ideas how you would go about designing the YAML schema.

There were some ideas in https://github.com/HPC-buildtest/buildtest-framework/wiki/Yaml-Schema-Draft i had but now these yaml are out-of date. I never found a YAML schema that i liked

**Comment by vsoch** [comment]
I would use the Github / Travis / Circle CI matrix idea as a start.

**Comment by shahzebsiddiqui** [comment]
Yep i had looked at Travis way back when i was thinking of this idea. I am wondering if we should move this to schema. Ideally i would like a schema that we agree. Once it's done would be updated in schema then buildtest-framework, then refactor code.

**Comment by vsoch** [comment]
Here is matrix builds for GitHub CI https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/#matrix-builds

**Comment by shahzebsiddiqui** [comment]
What about this idea? 
```
version: 0.0.1
module_matrix_example:
  type: script
  matrix:
    module: 
      - [ "module purge", "module load gcc/6.4"]
      - ["module load gcc/7.2"]
  run |
  ${{ matrix.module }} 
  gcc --version
```

I take it ``${{ }}``  are used to reference a YAML variable in this case ``matrix.module`` is a variable. I think this is a bit too simple, for now i just want permutation for modules, but certainly i can see multi-variable matrix permutation. That would be nice but too complex for initial design.

**Comment by vsoch** [comment]
So is the idea that:

 - we loop through the matrix, and for each variable listed (e.g., module) we loop through that so the run index 0 gets the content of module[0] (two lines, one to purge and one to load) and then run index 1 gets the single module load command? 

Did you consider what github does which is to have each line correspond to one run, and include all variables? I think that's more straight forward than what I see above. Then we can be sure that the first line corresponds to run 1, and we see all the variables defined within it.

**Comment by shahzebsiddiqui** [comment]
Yes i created this as a nested list so each element is a list of module commands to inject into the ``run``. At the moment we allow a string so user can write whatever they want but maybe there should be a better design where we don't specify ``module load`` and just focus on the name of module and it implicitly loads it. 

This is the part where i need some help and creativity in the YAML design. I think module permutation would be a common operation. Some other operation i see are running same test with mutliple argument, or a single test permutation across a variable.

Let's say compiling a single test with different compiler flags so that we can do matrix build without much overhead of duplicating a test. 

I don't like my proposed YAML design so i'd be open to exchange some ideas on some YAML examples to address this problem.

**Comment by vsoch** [comment]
yeah I'll give this a shot! I want to look over the few matrix strategies I know to double check. I have a meeting now but will do this later this afternoon. It's super cool we are adding a matrix!

**Comment by shahzebsiddiqui** [comment]
Take your time I think we would need to decide which task to proceed first since both will require some changes to the framework . Either this  issue or https://github.com/HPC-buildtest/schemas/issues/25. 

I see both task would require some work on schema then validation with some examples. Whichever of the two is easy from schema point of view seems to be a good candidate.

**Comment by vsoch** [comment]
Okay just to review the types in the wild, GitHub has a setup similar to yours, but has a single list of items per variable name:

```yaml
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [8, 10, 12]
        os: [ubuntu-latest, windows-latest, macos-latest]
```
And this would mean that versions 8, 10, and 12 would be tested for each of windows, ubuntu, and macos. For your example, this doesn't make sense because you have a list (done via dashes) under a variable name that includes another list. If we mapped this into "GitHub syntax" it would be something like:

```yaml
version: 0.0.1
module_matrix_example:
  type: script
  matrix:
    module: [ "module purge\nmodule load gcc/6.4", "module load gcc/7.2"]
  run |
  ${{ matrix.module }} 
  gcc --version
```
We could technically use your "list of lists" strategy, but that might be confusing for the user, because they look very different. We would then need to check, every time, if the user has provided a list with str/int content, or a list of lists. And then if we had a list of lists, what would be the default action when the user says `{{ matrix.module }}` - to join them by newline? This doesn't make sense, because the user needs to be able to understand very easily how what they are specifying as a string maps into the recipe printed. The reason we are running into this is because the example you provided above with multiple lines of modules (or more generally, lines to be added to a recipe) is _not_ the intended use case for a matrix. A matrix holds a clean listing of variables, and then all combinations are tested. A matrix is not intended for multiple lines of a script to be printed.

So for matrix, this is the pattern I'd like to see:

```yaml
version: 0.0.1
module_matrix_example:
  type: script
  matrix:
      node_version: [8, 10, 12]
      os: [ubuntu-latest, macos-latest]
  run: |
      echo "${{ matrix.os }}"
      echo "${{ matrix.node_version }}"
```

If the user really wanted to do some hack to define variables with newline, that would be up to him/her. And it would need to be if, under the case that matrix is supported, a single run is replaced with N runs. 

And the module commands, as I mentioned before, should be specified with the slurm schema, they are not a good use case for a matrix.

**Comment by shahzebsiddiqui** [comment]
Thanks for the detailed explanation, to sum it up i don't think list of list is good strategy using ``modules`` in a matrix. I think this issue looks more like a parameter test where module is a parameter to the ``run`` section (i.e test script).

Maybe the test name ``module_matrix_example`` need a key for passing parameters. I think we may need some way to name the parameters so that ``run`` can reference them. Just thinking out load, does this even make sense 

Or one idea is to have parameter as part of global schema with key that must match name of test block.  

```
version: 0.0.1
parameters:
  module_matrix_example:
    - "module purge; module load gcc/6.4"
    - "module load gcc/7.2"
module_matrix_example:
  type: script
  matrix:
    module: [ "module purge\nmodule load gcc/6.4", "module load gcc/7.2"]
  run |
  gcc --version

```

One last idea i had was maybe pass arguments to test ``/bin/bash test.sh arg1 args2`` and process each argument in shell script via ``sys.args`` in run section.
