### ISSUE TITLE
slurm schema needs to be developed

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#295]
Since we don't have a way to inject sbatch keys at the moment if user specify in ``run`` section as follows

```
job_test:
  description: Hello World example with OpenMP using gnu compiler
  type: script
  env:
    srcdir: $WORK/buildtest-stampede2/tests/apps/openmp/src
    exe: hello_sbatch
  run: |
    #SBATCH -N 1
    #SBATCH -n 1
    #SBATCH -p normal
    #SBATCH -t 00:10
    gcc -fopenmp -o $exe $srcdir/omp_hello.c
    OMP_NUM_THREADS=2
    ./$exe
```

The generated script is the following

```
(buildtest-framework) login4.stampede2(1113)$ cat .buildtest/hello/job_test.sh
#!/bin/bash
srcdir=$WORK/buildtest-stampede2/tests/apps/openmp/src
exe=hello_sbatch
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -p normal
#SBATCH -t 00:10
gcc -fopenmp -o $exe $srcdir/omp_hello.c
OMP_NUM_THREADS=2
./$exe
```

The #SBATCH keys need to be specified via executor and  buildtest needs to add them before added at the top even before the environment section. If not we will get an error when running the script. Reordering the sbatch directive on top we will get the job submitted properly.
