### ISSUE TITLE
compiler support 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#296]
It would be nice to have buidtest support compiler types which picks the appropriate compiler wrapper and just alters variable ``cc``, ``fc``, ``cxx``, ``cflags``, ``cxxflags``, ``ldflags``. For initial support we can try to support ``gnu``, ``intel``, ``pgi``, ``cuda`` and ``clang``.  

The way compilers could work is take a single test and allow user to compile with different compilers so that test doesn't have to be duplicated.

Here is a typical example for compiling vector addition with different compilers

```
version: 0.0.1
hello_gnu:
  type: script
  description: vector addition using gnu compiler
  env: 
    cc: gcc
    cflags: -O2
    ldflags: -lm
    srcdir: apps
    exe: vecAdd
  run: |
    module load gcc
    $cc $cflags -o $exe $srcdir/vecAdd.c $ldflags
    ./$exe 
 
hello_intel:
  type: script
  description: vector addition using intel compiler
  env: 
    cc: icc
    cflags: -O2
    ldflags: -lm
    srcdir: apps
    exe: vecAdd
  run: |
    module load intel
    $cc $cflags -o $exe $srcdir/vecAdd.c $ldflags
    ./$exe 
```

Given that above code is repetitive, we should allow some form of compiler selection that sets these variable such that they can be referenced in ``run`` section. I think buildtest should use the ``compiler`` key to just set the variables similar to what is done in ``env`` section that declares environment variable. 

Here is a proposal schema that supports gnu and intel compiler. The required key is ``cc``, ``fc`` or ``cxx`` so user can specify which one they want based on source file they compiling. We have a ``module`` key to allow user to specify a module to load based on the compiler. Down side with this approach is we can't specify multiple gnu compilers to test.

```
version: 0.0.1
hello_compiler_example:
  type: script
  description: vector addition using gnu and intel compiler
  compiler:
    gnu:
      module: |
          module purge
          module load gcc/7.0
      cc: gcc
      cflags: -O2
      ldflags: -lm
    intel:
      module: |
        module purge
        module load intel/18     
      cc: icc
      cflags: -O2
      ldflags: -lm
  env: 
    srcdir: apps
    exe: vecAdd
  run: |
    $cc $cflags -o $exe $srcdir/vecAdd.c $ldflags
    ./$exe 
```

Here is an approach for a more nested compiler structure. Inside ``gnu`` and ``intel`` we have a list of objects where each object is a pattern type such as ``gcc/7.0`` and ``gcc/6.0``. These names would be tacked on to the test or part of the output report.

With this approach we can support multiple compiler instances but top level key like ``gnu``, ``intel`` would have to be pre-defined.

```
version: 0.0.1
hello_compiler_example:
  type: script
  description: vector addition using gnu and intel compiler
  compiler:
    gnu:
    - gcc/7.0: 
        module: |
            module purge
            module load gcc/7.0
        cc: gcc
        cflags: -O2
        ldflags: -lm

   - gcc/6.0:
       module: |
            module purge
            module load gcc/6.0
       cc: gcc
       cflags: -O1 -Wall
       ldflags: -lm

    intel:
      intel/18: 
        module: |
          module purge
          module load intel/18     
        cc: icc
        cflags: -O2
        ldflags: -lm
  env: 
    srcdir: apps
    exe: vecAdd
  run: |
    $cc $cflags -o $exe $srcdir/vecAdd.c $ldflags
    ./$exe 
```

Here is an extension to previous design but with ability to avoid redefining variables if they are same across compiler group (``gnu``) or all compilers via use of ``commons`` key. 

```
version: 0.0.1
hello_compiler_example:
  type: script
  description: vector addition using gnu and intel compiler
  compiler:
    gnu:
      commons:
        cc: gcc
        cflags: -O2
        ldflags: -lm
      spec:
      - gcc/7.0: 
           module: |
             module purge
             module load gcc/7.0
     - gcc/6.0:
          module: |
            module purge
            module load gcc/6.0       
          cflags: -O1 -Wall

    intel:
      spec:
      - intel/18: 
          module: |
            module purge
            module load intel/18     
          cc: icc
          cflags: -O2
          ldflags: -lm
  env: 
    srcdir: apps
    exe: vecAdd
  run: |
    $cc $cflags -o $exe $srcdir/vecAdd.c $ldflags
    ./$exe 
```

The ``commons`` is a shared across group of gnu or intel it's optional, but user can override commons in the case of ``gcc/6.0`` where ``cflags`` was set to ``-O1 -Wall``. 

In this case we had to introduce a new key in this case ``spec`` which is under each compiler group which is a  list of objects.

I realize this can get more complex with what it already is, but this is an idea what i had in mind. The ``module`` key is used to specify a list of modules to load as is. This would get injected into the ``run`` section but at the moment user has no control in what order this is placed. Generally modules are placed right after ``#SBATCH`` directives but user is not aware of this.

Last one is an example but with shared common across all compilers

```
version: 0.0.1
hello_compiler_example:
  type: script
  description: vector addition using gnu and intel compiler
  compiler:
    commons:
      cflags: -O2
      ldflags: -lm
    gnu:
      commons:
        cc: gcc
      spec:
      - gcc/7.0: 
           module: |
             module purge
             module load gcc/7.0    

    intel:
      spec:
      - intel/18: 
          module: |
            module purge
            module load intel/18     
          cc: icc
  env: 
    srcdir: apps
    exe: vecAdd
  run: |
    $cc $cflags -o $exe $srcdir/vecAdd.c $ldflags
    ./$exe 
```

**Comment by shahzebsiddiqui** [comment]
@vsoch  One thing that bothers me with ``compiler`` schema is it's limitation on how content is generated. User can't do much tweaking on the content if they want to run some ad-hoc command in the middle of the script.  Is it possible to define our own variable replacement and introduce a  ``run`` section.

Just thinking out loud is it possible to define pre-defined tags that can be replaced in ``run`` section if user wants to further customization of test. For example, we make the framework load the modules before loading the test and this is not something user can control. If user wants to run a command between module load and start of compilation, not sure how they can do it without some variable substitution. 

```
version: 0.0.1
hello:
  type: compiler
  source: src/hello.c
 module:
    - "module purge && module load GCC"
  compiler:
    gnu:
      cflags: -Wall
  run:
    echo Start Test
    {{module}}
    gcc --version
    {{compile}}
    {{run}}
    echo Finish Test
```

**Comment by vsoch** [comment]
That would work! You could make a small namespace of sections that are known, and spit out an error if something is provided that is not (e.g., `{{notknown}}`. If you need variable substitution within there too, then I'd also consider namespacing the template subs (e.g., `{{ env.name }}` or `{{ section.name }}` akin to how it works with GitHub actions. And what would happen / be the default if no sections are included like that?

**Comment by vsoch** [comment]
I did something like that for gridtest -> https://vsoch.github.io/gridtest/getting-started/templates/#input-types although slightly different context.

**Comment by shahzebsiddiqui** [comment]
I am thinking of moving the ``exec_args`` up one, instead of being part of each compiler definition it is part of ``compiler`` property. I don't see why we need to group this in the compiler definition since exec_args is compiler agnostic. 

Currently we have

```
compiler: 
  source: hello.c
  gnu:
    exec_args: "1 2"
```

I propose we change to 

```
compiler:
  source: hello.c
  exec_args: 1 2 
  gnu: 
     cflags: "-Wall"
```

What do you think

**Comment by vsoch** [comment]
What exactly does exec_args refer to? A test run after the compile or build is done?

**Comment by shahzebsiddiqui** [comment]
exec_args is used to pass argument to compiled binary. This would be doing

``./a.out 1 2 3``

Right now we only doing ``./a.out``

**Comment by vsoch** [comment]
If there is a run of the binary after it is built it should be another section in the config. I don’t think it makes sense to couple them together, but take a modular approach.

**Comment by shahzebsiddiqui** [comment]
Just thinking out loud what about. Adding this under ``run`` section there could be other things we could do in run but basically it controls how the run line is generated.

```
compiler:
  source: hello.c
  run: 
    args: 1 2 
  gnu: 
     cflags: "-Wall"
```
