### ISSUE TITLE
job dependency

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#657]
@adityakavalur: let me know your thoughts

job dependency support only supported within single buildspec. I see some scenarios user may be interested in
 - Run jobB if jobA *pass* or *fail*
 - Run job based on custom script
 -  Run job based on certain exit code

## Job Dependency based on test state

Job dependency using the **depends** is name of test name to depend upon. In this case job is run once jobA is complete

```
version: "1.0"
buildspecs:
  jobA:
    type: script
    executor: local.bash
    description: job dependency
    run: python script.py

  jobB:
    type: script
    executor: local.bash
    description: job dependency
    depends: jobA
    run: python script.py
```

Another option, we can have `depends` as dict in this case we can trigger jobs based on job state. The `name` is test name and `state` is state of test `PASS` or `FAIL` depending on the output. It will trigger job based on these conditions

```
version: "1.0"
buildspecs:
  jobA:
    type: script
    executor: local.bash
    description: job dependency
    run: python script.py

  jobB:
    type: script
    executor: local.bash
    description: job dependency
    depends: 
       name: jobA
       state: PASS
    run: python script.py
```

## Job dependency based on returncode

```
version: "1.0"
buildspecs:
  jobA:
    type: script
    executor: local.bash
    description: job dependency
    run: python script.py

  jobB:
    type: script
    executor: local.bash
    description: job dependency
    depends: 
       name: jobA
       returncode: 1
    run: echo "JobB depends on jobA"
```

## Job dependency based on arbitrary script

In this case `name` is not required field

```
version: "1.0"
buildspecs:

  jobA:
    type: script
    executor: local.bash
    description: job dependency on custom script
    depends: 
       script: | 
          which echo
          which sbatch
    run: echo "JobB depends on script"
```
