### ISSUE TITLE
change executor property to be a list

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#658]
@adityakavalur let me know your thoughts

currently executor selects how test is run, the executor property is a string which locks test to a single executor let's change it to a list so a single test can be run on multiple executors

```
version: "1.0"
buildspecs:
  multi_executor:
    type: script
    executor: [slurm.haswell, slurm.knl]  
    sbatch: ["-N 1", "-t 30" ]
    run: hostname
```

This test will run on two executors `slurm.haswell` and `slurm.knl`. The script will be same for both executors just run on different queues. I foresee this may not work if we intermix different shells `local.bash`, `local.csh`, `local.zsh`, `local.python`. I think this should be used only with batch executors.

if we need custom values per executor for `sbatch`, `batch`, `lsf`, `cobalt` property we would need to change these properties. I don't know if other properties would be worth changing if user want custom behavior per executor

See https://buildtesters.github.io/buildtest/pages/devel/schemadocs/script-v1.html
