### ISSUE TITLE
pass condition based on runtime

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#735]
The idea of this feature is determine status of test (`PASS`, or `FAIL`) based on runtime of test. The user can specify a min and max value for runtime if it falls within the range the test will pass otherwise it fails.

The `min` and `max` are optional but one must be specified. In example below we specify both

```
version: "1.0"
buildspecs:
  timelimit_min_max:
    type: script
    executor: generic.local.sh
    description: "Run a sleep job for 2 seconds and test pass if its within 1.5-3.0sec 
    run: sleep 2
    status:
      runtime:
        min: 1.5
        max: 3.0
```

In this example the test must pass if its runtime is greater than min time

```
version: "1.0"
buildspecs:
  timelimit_min:
    type: script
    executor: generic.local.sh
    description: "Run a sleep job for 2 seconds and test pass if its exceeds min time
    run: sleep 2
    status:
      runtime:
        min: 1.5
```

Similarly if `max`  is specified without `min` it will pass if runtime is within maximum runtime

```
version: "1.0"
buildspecs:
  timelimit_min:
    type: script
    executor: generic.local.sh
    description: "Run a sleep job for 5 seconds and test pass if it's within max time
    run: sleep 2
    status:
      runtime:
        max: 5
```
