### ISSUE TITLE
Spack buildsystem 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#757]
We can add a spack buildsystem in order to install and test spack packages in buildtest. buildtest can interface with spack to support the batch scheduler since it knows how to submit and poll job and gather results, while `spack test` is only meant to run tests without the scheduling support.  

We can extend buildtest to add another schema using `type: spack` so that we can write buildspecs with the spack buildsystem.

# Current Support 
Currently we `script` schema to define shell script style for running tests for instance this test does a simple test using spack commands
    
<img width="623" alt="Screen Shot 2021-05-25 at 5 30 31 PM" src="https://user-images.githubusercontent.com/12942230/119571074-ea568600-bd7e-11eb-805b-a0f00914a9f9.png">

We also have support for running spack through batch scheduler in this test https://github.com/buildtesters/buildtest-cori/blob/devel/buildspecs/apps/spack/tmp_filesystem_spack_test.yml see below. This is done via `sbatch` and `executor` property.

<img width="672" alt="Screen Shot 2021-05-25 at 8 38 46 PM" src="https://user-images.githubusercontent.com/12942230/119585702-36162900-bd99-11eb-9af0-ed797df02e69.png">

# Installing specs without an environment

The `spack` is a *required* keyword to specify location of where spack lives on the filesystem. The `install` property that interface with `spack install` command. One can specify a list of specs to install 
```
version: "1.0"
buildspecs:
  spack_install:
    type: spack
    executor: generic.local.sh
    spack: /path/to/spack
    install:
      specs: ['zlib', 'm4']
```

This will create a test 

```
source /path/to/spack/share/spack/setup-env.sh
spack install zlib
spack install m4
```

You can also pass `options` to the `spack install`, for instance if we want to add `--no-cache` option to `spack install` we can specify this as follows

```
version: "1.0"
buildspecs:
  spack_install:
    type: spack
    executor: generic.local.sh
    spack: /path/to/spack
    install:
      options: '--no-cache'
      specs: ['zlib', 'm4']
```
# Installing specs in an environment

The `env` property can be used to manage with spack environment `spack env`. The user can create an environment and add specs using the `specs` property. When using a spack environment one must use the `create` option which will follow the `spack env create` option. One can create a spack environment using a name, directory and using a manifest file (`spack.yaml`, `spack.lock`).

```
version: "1.0"
buildspecs:
  spack_build_system:
    type: spack
    executor: generic.local.sh
    spack: /path/to/spack
    env: 
      create:
         name: 'e4s'
      specs: ['zlib','m4']    
```

This will create a script something as follows. We will ensure buildtest automatically activates the environment.

```
source /path/to/spack/share/spack/setup-env.sh
spack env create -n e4s 
spack env activate e4s
spack add zlib
spack add m4
spack install
```

# Installing specs from a spack.yaml

The `manifest` property can be used to create a spack environment from an existing `spack.yaml` that user wants to provide. The user must specify path to `spack.yaml` and buildtest will attempt to create an environment.
```
version: "1.0"
buildspecs:
  spack_build_system:
    type: spack
    executor: generic.local.sh
    spack: /path/to/spack
    env: 
      create:
         name: e4s
         manifest: /path/to/spack.yaml
```

This will create a test as follows

```
source /path/to/spack/share/spack/setup-env.sh
spack env create -n e4s /path/to/spack.yaml
spack env activate e4s
spack install
```

The `manifest` property can be path to `spack.yaml` or `spack.lock`.

# environment creation using a directory

Similarly user can create an environment using a directory 
```
version: "1.0"
buildspecs:
  spack_build_system:
    type: spack
    executor: generic.local.sh
    spack: /path/to/spack
    env: 
      create:
         dir: /path/to/dir
         specs: ['zlib@1.2.8%gcc', 'm4']
```

This will create a test as follows

```
source /path/to/spack/share/spack/setup-env.sh
spack env create -d /path/to/dir 
spack env activate /path/to/dir
spack add zlib@1.2.8%gcc
spack add m4
spack install
```

# options to `spack env create` 

If user wants spack to pass any other options from `spack env create` not supported by buildtest we can use the `opts` option within `create`. For instance the current `spack env create` supports a few options such as `--without-view` 
```
usage: spack env create [-hd] [--keep-relative]
                        [--without-view | --with-view WITH_VIEW]
                        env [envfile]

positional arguments:
  env                   name of environment to create
  envfile               optional init file; can be spack.yaml or spack.lock

optional arguments:
  -h, --help            show this help message and exit
  -d, --dir             create an environment in a specific directory
  --keep-relative       copy relative develop paths verbatim into the new environment when initializing from envfile
  --without-view        do not maintain a view for this environment
  --with-view WITH_VIEW
                        specify that this environment should maintain a view at the specified path (by default the view is maintained in the environment directory)
```

The `options` under `create` property will pass options to `spack env create`

```
version: "1.0"
buildspecs:
  spack_build_system:
    type: spack
    executor: generic.local.sh
    spack: /path/to/spack
    env: 
      create:
         options: '--without-view'
         dir: /path/to/dir
         specs: ['zlib@1.2.8%gcc', 'm4']
```

This will create the following test

```
source /path/to/spack/share/spack/setup-env.sh
spack env create --without-view -d /path/to/dir 
spack env activate /path/to/dir
spack add zlib@1.2.8%gcc
spack add m4
spack install
```

# pre_cmd and post_cmd for running arbitrary shell commands

We can alternately let user run any arbitrary command using `pre_cmd` and `post_cmd` to allow for any specific shell commands to run

```
version: "1.0"
buildspecs:
  spack_build_system:
    type: spack
    executor: generic.local.sh
    spack: /path/to/spack
    pre_cmd: |
      FOO=BAR
      echo $FOO
    env: 
      create:
         dir: /path/to/dir
         specs: ['zlib@1.2.8%gcc', 'm4']
    post_cmd: | 
      HELLO=WORLD
      echo $HELLO
```

This will run the `pre_cmd` before spack and `post_cmd` after spack commands

```
FOO=BAR
echo $FOO
source /path/to/spack/share/spack/setup-env.sh
spack env create -d /path/to/dir 
spack env activate /path/to/dir
spack add zlib@1.2.8%gcc
spack add m4
spack install
HELLO=WORLD
echo $HELLO
```

# batch properties

The following batch properties `sbatch`, `pbs`, `cobalt`, `lsf`, `batch`  for defining scheduler directives can be available for spack build system. This is documented in https://buildtest.readthedocs.io/en/devel/buildspecs/batch_support.html. An example test can be as follows

```
version: "1.0"
buildspecs:
  spack_build_system:
    type: spack
    executor: cori.slurm.haswell_debug
    spack: /path/to/spack
    sbatch: ["-N 1", "-t 10", "-n 4", "-C haswell"]
    env: 
      create:
         dir: /path/to/dir
         specs: ['zlib@1.2.8%gcc', 'm4']
```

This test will be run with executor `cori.slurm.haswell_debug` which has a queue name `debug` so test will be executed with `sbatch -q debug`
```
#SBATCH -N 1
#SBATCH -t 10
#SBATCH -n 4
#SBATCH -C haswell
source /path/to/spack/share/spack/setup-env.sh
spack env create -d /path/to/dir 
spack env activate /path/to/dir
spack add zlib@1.2.8%gcc
spack add m4
spack install
```

Inherited Properties

- The `status` property will be inherited in the spack schema for returncode matching or matching output/error such as see https://buildtest.readthedocs.io/en/devel/buildspecs/buildspec_overview.html#return-code-matching  and https://buildtest.readthedocs.io/en/devel/buildspecs/compiler.html#tweak-how-test-are-passed
- The `skip` property will be inherited see https://buildtest.readthedocs.io/en/devel/buildspecs/buildspec_overview.html#skipping-test

# Things to do
- Add schema file in https://github.com/buildtesters/buildtest/tree/devel/buildtest/schemas named `spack-v1.0.schema.json`
- Add regression test for schema in https://github.com/buildtesters/buildtest/tree/devel/tests/schema_tests with example valid and invalid tests in https://github.com/buildtesters/buildtest/tree/devel/buildtest/schemas/examples
- Add a spack build system class in https://github.com/buildtesters/buildtest/tree/devel/buildtest/buildsystem to implement buildspecs using `type: spack`.
