### ISSUE TITLE
metrics property

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#817]
1. Please describe your feature request with example buildspec example

We need a way to define multiple metrics that can be captured in the report file that can be queried. The metrics can be defined as variables predefined in the test or through some regular expression. There will be a field `metric` that can be as follows. The sub-key must be name of the metric which is assigned a name and recorded in the report file. The name of the metric is **perf_gflops**. Each metric can be of one of two types either a variable assignment as shown below. The `variable` keyword will assign value `GFLOPS` to `perf_gflops`. 

```
metric_variable_assignment:
    executor: generic.local.sh
    type: script
    description: capture result metric from environment variable
    run: export GFLOPS=63.6515
    tags: tutorials
    metrics:
       perf_gflops:
         variable: GFLOPS
```

We can also define a metric that reads from output or error file and use a regular expression. In this example we have a metric name **hpcg_result** which will apply a regular expression on stdout and store the value **rating of=63.6515** for metric **hpcg_result**.

```
metric_regex_example:
    executor: generic.local.sh
    type: script
    description: capture result metric from output
    run: echo "HPCG result is VALID with a GFLOP/s rating of=63.6515"
    tags: tutorials
    metric:
      hpcg_result:
        exp: "rating of=(\d+\.\d+)$"
        stream: stdout
```

We can define multiple metrics in the same test take for instance this example below is a combination of variable assignment and regular expression. The metric must be unique names. 

```
metric_regex_variable_example:
    executor: generic.local.sh
    type: script
    description: capture result metric from output
    run: |
      export GFLOPS=63.6515
      echo "HPCG result is VALID with a GFLOP/s rating of=63.6515"
    tags: tutorials
    metric:
       perf_gflops:
         variable: GFLOPS
      hpcg_result:
        exp: "rating of=(\d+\.\d+)$"
        stream: stdout
```
2. Is this feature a global definition which is inherited by multiple schemas (YES/NO) ?

YES

3. Is this feature applicable for buildtest settings (``settings.schema.json``)  ? 

NO

4. Is this feature applicable for existing schemas, please select which one?

- [X] script-v1.0.schema.json
- [X] compiler-v1.0.schema.json
- [X] spack-v1.0.schema.json
- [ ] None of the Above
