### ISSUE TITLE
[FEATURE]: dynamic range of procs and nodes

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#859]
### Please describe your feature request

There should be an option to specify procs and nodes on command line that works for all schedulers (LSF, Slurm, PBS, Cobalt). The option can be `buildtest build --nodes` and `buildtest build --procs` or another option is `buildtest build --cpus` instead of `--procs`. The values will be comma separated list of process + node configuration that get injected into the script. In example below we will run this test with 2, 4, 6 processors. 

```
buildtest build -b hostname.yml --procs 2,4,6
```

We will honor the original request for the buildspec and add additional tests for the different range let's assume we have the following 

which runs on 1 processor we will have *3* additional test which will add `#SBATCH -n 2`, `#SBATCH -n 4`, `#SBATCH -n 6` to the test. We will need to detect in the `sbatch` list for string that contains `-n` so we don't have double counts for `#SBATCH -n` values.

```
version: "1.0"
buildspecs:
  hostname_knl:
    type: script
    executor: cori.slurm.knl_debug
    description: "Run hostname via KNL debug queue"
    sbatch: ["-t 5", "-n 1"]
    run: hostname
```

Another option is to add option in the executor setting to specify a range of processors. Right now here is a definition of haswell_debug queue. 

```
      slurm:
        haswell_debug:
          qos: debug
          cluster: cori
          options:
          - -C haswell
          description: debug queue on Haswell partition
```

The proposed solution would be to attach `procs` and `nodes` as a list of integers as follows. Whenever buildtest runs a test using the executor `cori.slurm.haswell_debug` then buildtest can permutate across the node+proc subspace. By default, we wouldn't honor this feature but enable it as part of an option maybe `buildtest build --enable-scaling` which will run scaling test for each test using this executor.

```
      slurm:
        haswell_debug:
          qos: debug
          cluster: cori
          procs: [ 1, 2, 4, 8]
          nodes: [ 1, 2 ]
          options:
          - -C haswell
          description: debug queue on Haswell partition
```

### Post question in Slack

- [X] I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue

### Is there an existing issue

- [X] I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue
