### ISSUE TITLE
email integration 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#86]
Add support for email integration. This can be set in config.yaml as follows

```
BUILDTEST_EMAIL: True
EMAIL:
   - SENDER: user@company.com
   - FROM: user1@company.com
   - SUBJECT: BUILDTEST ALERT
```

If ``BUILDTESDT_EMAIL: True``  is set buildtest will send email for test runs that fall below threshold (``BUILDTEST_SUCCESS_THRESHOLD``).  

This command should work when running tests (``_buildtest run``)
