### ISSUE TITLE
add support for 'max_jobs'

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#866]
The executor configuration supports max_jobs that can be defined under 'defaults' or per executor setting. Which controls number of jobs that can be run at a given time. The `max_jobs` under `defaults` is inherited but can be overridden per executor section currently we can define something as follows

In this example the default is 1 job that can be run concurrently for `csh` executor for `bash` it will be 2 concurrent jobs for `sh` it will be 3 concurrent jobs. 
```
    executors:
      defaults:
        max_jobs: 1
      local:
        bash:
          description: submit jobs on local machine using bash shell
          shell: bash
          max_jobs: 2

        sh:
          description: submit jobs on local machine using sh shell
          shell: sh
          max_jobs: 3

        csh:
          description: submit jobs on local machine using csh shell
          shell: csh
```
