### ISSUE TITLE
support single test with multiple compilers

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#88]
This could be a simple hello world program in YAML file that user may want to compile against different compilers

```
source: hello.c
testblock:
  test:
    name: hello_c_gcc
    compiler: gcc
    buildopts: -O2
    module:
    - gcc
    name: hello_c_gcc_system
    compiler: gcc
    buildopts: -O2
    module:
    - system
  test:
    name: hello_c_intel
    compiler: intel
    buildopts: -O3
    module:
    - intel
  test:
    name: hello_c_pgi
    compiler: pgi
    buildopts: -O1 
    module: 
    - pgi
```

The YAML file should create 4 different scripts that may look as follows

Script: ``hello_c_gcc``
```
#!/bin/sh
module purge
module load gcc
gcc -O2 hello.c -o hello_c_gcc
./hello_c_gcc
```
Script: ``hello_c_gcc_system`` this will use system gcc and no modules will be loaded
```
#!/bin/sh
module purge
gcc -O2 hello.c -o hello_c_gcc_system
./hello_c_gcc_system
```
Script: ``hello_c_intel`` this will use intel module
```
#!/bin/sh
module purge
module load intel
icc -O3 hello.c -o hello_c_intel
./hello_c_intel
```

Script: ``hello_c_pgi`` this will use pgi module
```
#!/bin/sh
module purge
module load pgi
pgcc -O1 hello.c -o hello_c_pgi
./hello_c_pgi
```
