### ISSUE TITLE
running python test under virtual environment

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#89]
The ``testblock: python2`` should be a class that will parse this yaml configuration and return a test script to run Python 2.x code. 

A similar testblock can be implemented for python3 where pip, virtualenv will be compatible for python3 and assuming python script that is to be run is python 3 compatible.
 
The configuration below could have support for virtual environment as yaml keys to allow user to configure the virtual environment before running the python code.

```
testblock: python2
source: random.py
pyver: 2.6, 2.7, 2.7.10, 2.7.15
virtualenv: yes
virtualenvopts:
  name: venv1
  download: yes
  no-site-packages: yes
  python: /usr/bin/python

pythonpackages:
  - numpy
  - scipy

testblock:
  name:  random
  
```
The script will be named ``random.sh`` with the following content
```
#!/bin/sh
virtualenv --download --no-site-packages -p /usr/bin/python venv1
source $HOME/venv1/bin/activate
pip install numpy scipy
python random.py
```
