### ISSUE TITLE
buildtest test variants  

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest#92]
buildtest variants could enhance test scripts by writing a different test for each permutation initial support can start out by doing flag variants to build test with different compiler flags 

```
testblock: singlesource
test:
    source: hello.cpp
    compiler: gnu
    variants:
      flags:
        - O3
        - O2
        - O1 
    module:
      - gcc
```

A test variant for compilers may look as follows for a OpenMP example

```
testblock: singlesource
test:
    source: omp_mm.c
    vars:
        OMP_NUM_THREADS: 4
    variants:
      compiler: gnu
         ldflags: "-fopenmp"
         module: 
           - gcc
       compilers: intel
         ldflags: "-qopenmp"
         module:
           - intel
       compiler: pgi
         ldflags: "-mp"
         module: 
            - pgi
```

To compile a openmp example with gcc, intel and pgi it will require different flags.

``gnu``: ``gcc -fopenmp omp_mm.c -o omp_mm``
``intel``: ``icc -qopenmp omp_mm.c -o omp_mm``
``pgi``: ``pgi -fopenmp omp_mm.c -o omp_mm``

buildtest can create one test script per variant the naming scheme could be as simple as 
``omp_mm.c.yml.variant_<first 15 digits of sha256>.sh`` where omp_mm.c.yml is the yml file https://github.com/HPC-buildtest/buildtest-configs/blob/master/buildtest/suite/openmp/matrixmultiplication/omp_mm.c.yml to ensure unique names for test scripts
